language: python
python:
  - "3.5"
  - "3.6"

# restrict to branches
branches:
  only:
    - master
    - develop

# command to install python dependencies
install:
  # the features used in setup.cfg require at decent version of setuptools
  - python -m pip install --upgrade "setuptools>=40.0"

  # install dependencies for test
  - python -m pip install -e ".[tests]"

# command to run tests
script:
  # run tests
  - python -m coverage run setup.py test

  # show coverage stats
  - python -m coverage report -m

  # run code formatting tests
  - if [[ $TRAVIS_PYTHON_VERSION != 3.5 ]]; then python -m black . --check; fi
  - python -m flake8
